//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr2_Db_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackerySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackerySet()
        {
            this.DeliveriesSet = new HashSet<DeliveriesSet>();
            this.ShiftsSet = new HashSet<ShiftsSet>();
        }
    
        public int Id { get; set; }
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesSet> DeliveriesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftsSet> ShiftsSet { get; set; }

        public void BackerySetAdd (BackerySet backery)
        {
            using(BakeryEntities db = new BakeryEntities())
            {
                db.BackerySet.Add(backery);
                db.SaveChanges();
            }
        }
    }
}
