//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr2_Db_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveriesSet
    {
        public int Id { get; set; }
        public string adres { get; set; }
        public short numberOfCakes { get; set; }
        public int Backery_Id { get; set; }
    
        public virtual BackerySet BackerySet { get; set; }

        public void DeliveriesSetAdd(DeliveriesSet deliveries)
        {
            using(BakeryEntities db = new BakeryEntities())
            {
                db.DeliveriesSet.Add(deliveries);
                db.SaveChanges();
            }
        }
    }
}
