//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr2_Db_WF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakeryEntities : DbContext
    {
        public BakeryEntities(): base("name=BakeryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackerySet> BackerySet { get; set; }
        public virtual DbSet<DeliveriesSet> DeliveriesSet { get; set; }
        public virtual DbSet<ShiftsSet> ShiftsSet { get; set; }
        public virtual DbSet<StaffSet> StaffSet { get; set; }
    }
}
