//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr2_Db_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffSet()
        {
            this.ShiftsSet = new HashSet<ShiftsSet>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftsSet> ShiftsSet { get; set; }

        public void StaffSetAdd(StaffSet staff)
        {
            using(BakeryEntities db =  new BakeryEntities())
            {
                db.StaffSet.Add(staff);
                db.SaveChanges();
            }
        }
    }
}
